### ISSUE TITLE
Suggestion: Add sorting method

### ISSUE THREAD

**Issue by shakram02** [rydama/youtube-playlist-sorter#1]
What do you think about adding a dropdown menu where the user chooses a sorting method?

For example, I needed to sort the videos based on a number in the name
Another user mentioned that they wanted to do case insensitive matching,

Adding a drop-down menu to select a sorting method will make it easier to make a small PR request and add a method

**Comment by rydama** [comment]
@shakram02 good suggestion. Let me have a look, perhaps this weekend.

**Comment by rydama** [comment]
I updated the extension (v.0.0.7) to properly sort titles starting with numbers. Also now sorts case-insensitive. Hopefully this eliminates the need to have any kind of drop-down. Thanks for the inspiration to fix this long-standing issue 👍

**Comment by shakram02** [comment]
you're most welcome :)

For numerical sorting I used a slightly different methodology; ordering based on the first number that I find in the title, I did it in a quick and dirty way [here](https://github.com/shakram02/youtube-playlist-sorter/commit/67e64a50f49a83df9695d0e51f5a25dfbf7706a7#diff-7fc9f218a6a0ddc6b4bbba7841497b58R170) just because I was my only user. 
The argument that defends this method is that; assume you have lectures of videos of a tutorial series, the title of the video title will be on the form `lesson|chapter \d+ ...` so making the regex match only on the beginning of line ([src](https://github.com/rydama/youtube-playlist-sorter/commit/1e43d60b62612ac852662bf25e2f9e9905dd9ac4#diff-d3d88103d3a5c88006635c8eead798f7R4)) won't be very helpful in this case.

What do you think?
