### ISSUE TITLE
Suggestion: sorting by video length

### ISSUE THREAD

**Issue by zawette** [rydama/youtube-playlist-sorter#11]

**Comment by rydama** [comment]
UPDATE: Oct 5, 2024

This extension is no longer available in the Chrome extension store.

YouTube has revoked the Chrome extension's access to the YouTube API. YouTube audited the extension and required several changes that I am unable to, or will not, make (including changing the name of the extension and user interface to not use the word "YouTube"). I guess we'd have to call it "Playlist Sorter for That Really Popular Video Sharing Service". No thanks.

I'll leave the code here for now, in case anyone wants to run it locally, or make their own attempt with YouTube's auditors.
