### ISSUE TITLE
error format when A-Z sorting

### ISSUE THREAD

**Issue by MacCampers** [rydama/youtube-playlist-sorter#6]
400: Invalid value for: Invalid format: "2020-04-29T08:43:01Z" is malformed at "Z" 

![image](https://user-images.githubusercontent.com/46927825/80597547-4b027a80-8a28-11ea-9127-112e707b3491.png)

You also have an error sometimes (limit of daily request exceed or something like that, error 500 if i recall correctly).

Thanks anyway for the tool, very usefull, good work :) !

**Comment by MacCampers** [comment]
![image](https://user-images.githubusercontent.com/46927825/80597822-ad5b7b00-8a28-11ea-858d-431604d51e91.png)


for the same error

**Comment by rydama** [comment]
Thanks @MacCampers, I plan to take a look soon

**Comment by rydama** [comment]
I've got a fix for the invalid date format. I'll close this issue once the chrome extension store approves the new version.

Regarding the _"Encountered two children with the same key"_ error, I'm wondering if the playlist somehow has the same video in it twice. That's the only way I can see how that warning might happen.

Regarding the _"limit of daily request exceed"_ error, I can see that my api quota sometimes gets close to the limit. I will try to request more quota from youtube.

**Comment by rydama** [comment]
Fix is now in the chrome store https://chrome.google.com/webstore/detail/playlist-sorter-for-youtu/ameobkgafemjmlgobgbdadbdbgncbecg
